### ISSUE TITLE
Modification for KITTI raw data

### ISSUE THREAD

**Issue by langelesl** [mrtpk/lidar-buster#1]
Hello. Thanks for sharing your project. I used segmentation method to process the images from KITTI raw data and then marked the road part in image. I'm wondering if I could use your method to transform the prediction result (just like ground truth image of road benchmark) with calibration matrices of calibration files (velo_cam.txt, cam_cam.txt and imu_velo.txt) of raw data. I have seen that you used (u, v, 1) = P2 * R0_rect * Tr_velo_to_cam * (x, y, z, 1) to project point cloud on the image plane of camera 2.  But when I tried to use (u, v, 1) = P_rect_20 * R_rect_00 * T_cam0_velo * (x, y, z, 1) from calibration file of raw data to reproduce the projection result, he result was terrible. I'm not sure if I used the wrong equation here. Could you please give me some tips about how I should modify your codes of calibration part to show the road part of image in point cloud with raw data?
I would appreciate your help.

**Comment by mrtpk** [comment]
Dear Langelesl, 
I'm glad that you find my code helpful. I did not completely understand where you are facing the problem. Are you trying to project LiDAR points to images in KITTI raw dataset? I haven't done that but would love to check it out. Please feel to drop a mail to nivintpaul[at]gmail[dot]com. 
Regards,
Thomas.
